---

- name: Break website
  hosts: web_servers
  gather_facts: false
  become: true

  tasks:
    - name: Send debug message that the website is down
      ansible.builtin.debug:
        msg: "Website is down!"

    - name: Fix the webservice container
      containers.podman.podman_container:
        name: apache
        state: started