---

- name: Break website
  hosts: web_servers
  gather_facts: false
  become: false

  tasks:

    - name: Break the web service container
      containers.podman.podman_container:
        name: apache
        state: stopped

    - name: Send debug message that the website is down
      ansible.builtin.debug:
        msg: "Website is down!"