---

- name: Restore website
  hosts: web
  gather_facts: false
  become: true

  tasks:
    - name: Send debug message that the website is down
      ansible.builtin.debug:
        msg: "Website is down!"

    - name: Start web service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
