---

- name: Restore website
  hosts: web_servers
  gather_facts: false
  become: false
  vars:
    volume_path: podman

  tasks:
    - name: Send debug message that the website is down
      ansible.builtin.debug:
        msg: "Website is being restored"

    - name: Fix the webservice container
      containers.podman.podman_container:
        name: apache
        image: docker.io/httpd
        state: started
        volume:
          - "./{{ volume_path }}/:/usr/local/apache2/htdocs:z"
        ports:
          - "8081:80"

    - name: Check the web page
      register: web_output
      changed_when: false
      ansible.builtin.uri:
        url: http://127.0.0.1:8081
        return_content: true

    - name: Register output of podman ps
      register: podman_output
      changed_when: false
      ansible.builtin.command: podman ps

    - name: Output
      ansible.builtin.debug:
        msg:
          - "Output of podman ps command:"
          - "{{ podman_output.stdout_lines }}"
          - "Contents of web page:"
          - "{{ web_output.content }}"

    # - name: Start web service
    #   ansible.builtin.service:
    #     name: httpd
    #     state: started
    #     enabled: true

