---

- name: Restore website
  hosts: web_servers
  gather_facts: false
  become: false
  vars:
    volume_path: podman

  tasks:
    - name: Send debug message that the website is down
      ansible.builtin.debug:
        msg: "Website is down!"

    - name: Fix the webservice container
      containers.podman.podman_container:
        name: apache
        image: docker.io/httpd
        state: started
        volume:
          - "./{{ volume_path }}/:/usr/local/apache2/htdocs:z"
        ports:
          - "8081:80"

    # - name: Start web service
    #   ansible.builtin.service:
    #     name: httpd
    #     state: started
    #     enabled: true

