---

- name: Restart Filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted

- name: Reload auditd rules
  failed_when:
    - augenrules_result.rc != 0
    - "'No such file or directory' in augenrules_result.stderr"
  register: augenrules_result
  ansible.builtin.command: augenrules --load
