---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
     - ansible.eda.url_check:
        verify_ssl: false
        urls:
          - http://3.15.13.215
        delay: 10

  rules:
    - name: Web site is up
      condition: event.url_check.status == "up"
      action:
        debug:
          msg: "Site is up"

    - name: Web site is down
      condition: event.url_check.status == "down"
      action:
        debug:
          msg: "Site is down"