---

- name: Listen for STIG File Changes
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: web03.dperrone.dev
        port: 9092
        topic: eda-topic
        group_id: eda-demo-group
  
  rules:
    - name: Detect activity on /etc/shadow
      condition: event.message is search("shadow")
      action:
        run_playbook:
          name: remediate_stig.yml
          # Extract the hostname from the Filebeat JSON and pass it to AAP
          extra_vars:
            target_server: "{{ event.host.name }}"
            offending_message: "{{ event.message }}"