---

- name: Listen for STIG File Changes
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: web03.dperrone.dev
        port: 9092
        topic: eda-topic
        group_id: eda-demo-group

  rules:

    # - name: Catch Everything and Print to Log
    #   condition: true
    #   action:
    #     debug:
    #       msg: "RAW AAP EVENT PAYLOAD: {{ event }}"

    - name: Detect activity on /etc/shadow
      # Updated to look inside the 'body' wrapper
      condition: event.body.message is search("shadow")
      action:
        run_job_template:
          name: "EDA STIG Remediation" 
          organization: "Default"
          job_args:
            extra_vars:
              # Updated to extract the variables from inside 'body'
              target_server: "{{ event.body.host.name }}"
              offending_message: "{{ event.body.message }}"